apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/name: hello-world-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world-app
    spec:
      containers:
        - image: gcr.io/google-samples/hello-app:2.0
          name: hello-world
          ports:
            - containerPort: 8080
