apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-env-var
  labels:
    app.kubernetes.io/name: configmap-env-var
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: configmap-env-var
  template:
    metadata:
      labels:
        app.kubernetes.io/name: configmap-env-var
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          env:
            - name: XXX
              valueFrom:
                configMapKeyRef:
                  key: xxx
                  name: xxx
          command:
            - /bin/sh
            - -c
            - while true; do echo "$(date) I love $XXX"; 
              sleep 10; done;
          ports:
            - containerPort: 80

